# skaffold.yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: nomulus-crash
profiles:
- name: canary
  manifests:
    rawYaml:
    - ../jetty/kubernetes/nomulus-alpha-pubapi-canary.yaml
- name: stable
  manifests:
    rawYaml:
    - ../jetty/kubernetes/nomulus-alpha-pubapi.yaml
  deploy:
    kubectl: { }
